
server:
  port: 8081
# 激活了dev文档块
spring:
  profiles:
    active: dev
---
#---是指定文档块, 可以用profiles指定每一个文档块是什么类型的
server:
  port: 8083
spring:
  profiles: dev
debug: true
---
server:
  port: 8084
spring:
  profiles: produ


